
-- local todo = require("todo-comments")
-- map('n', ']t', function()
--    todo.jump_next()
--  end, { desc = "Next todo comment" })
--
--  map('n', '[t', function()
--    todo.jump_prev()
--  end, { desc = "Previous todo comment" })
--
--  map('n', ']t', function()
--    todo.jump_next({keywords = { "TODO", "FIX", "WARNING" }})
--  end, { desc = "Next error/warning todo comment" })

-- local map = vim.keymap.set
-- local scretch = require('0xJohnnyboy/scretch.nvim')
-- map('n', '<leader>sn', scretch.new)
-- map('n', '<leader>snn', scretch.new_named)
-- map('n', '<leader>sft', scretch.new_from_template)
-- map('n', '<leader>sl', scretch.last)
-- map('n', '<leader>ss', scretch.search)
-- map('n', '<leader>st', scretch.edit_template)
-- map('n', '<leader>sg', scretch.grep)
-- map('n', '<leader>sv', scretch.explore)
-- map('n', '<leader>sat', scretch.save_as_template)
